### ISSUE TITLE
3点 drop-down のコンポーネント化

### ISSUE THREAD

**Issue by abetatsu** [abetatsu/ODECOLOG#91]
# やること
- [x] 3点 drop-down のコンポーネント化
- [x] ルーティング、idの受け渡し
- [x] カレンダー月移動エラー修正

# 完了の定義
- 3点 drop-down のコンポーネント化され問題なく動作する

**Comment by masagao** [comment]
![LGTM](https://cdn.lgtmoon.dev/images/99879)
